### PR TITLE
Allow cronitor.sh to support environments

### PR DESCRIPTION
**Pull request by dudo**
cronitor.sh can now take -E as an argument.

### CODE REVIEW

**Comment by aflanagan** [comment]
Thank you! I see that the `-E` is used because `-e` was already taken. Certainly not opposed to this, but if you wanted to keep it all lowercase I'm also not opposed to changing the existing `-e` to a different variable name. This script isn't widely used, so I'm not worried about it causing breaking changes unless it does for you all.

**Comment by dudo** [comment]
I'm indifferent. This is really a copy/pasta kind of tool, so folks can change flags to their liking.

**Comment by erchn** [comment]
> Thank you! I see that the `-E` is used because `-e` was already taken. Certainly not opposed to this, but if you wanted to keep it all lowercase I'm also not opposed to changing the existing `-e` to a different variable name. This script isn't widely used, so I'm not worried about it causing breaking changes unless it does for you all.

There is already a `-S` also.

**Comment by aflanagan** [comment]
Yeah good points all around. Let's get this in there. Thanks for this!

**Pull request merged**
